### ISSUE TITLE
Cannot Find Symbol

### ISSUE THREAD

**Issue by pierfier** [Derrreks/SideScroller#1]
I am not sure if it is not working for you guys, but I figured out why it is not working. For some reason, I have to declare the object inside the main method. It should work anyways, but that is what's happening. I have a solution to it and I will let you guys try it before it is permenant.

**Comment by Derrreks** [comment]
I wouldn't be compiling it just yet; I'm still working out the frame and panels and nothing is connected so it really shouldn't be working yet.

**Comment by pierfier** [comment]
Sounds good! At least now I know why it was giving me this particular error.
