### ISSUE TITLE
Key Listening

### ISSUE THREAD

**Issue by Derrreks** [Derrreks/SideScroller#11]
We need to figure out how to be able to continue to listen to a key if they're holding it down. Right now I think it will only work once when they press it.

**Comment by pr0ves** [comment]
This could be a solution:
http://stackoverflow.com/questions/2623995/swings-keylistener-and-multiple-keys-pressed-at-the-same-time
Also you could implement KeyListener in the GamePanel class directly and use in the constructor addKeyListener(this)

**Comment by pr0ves** [comment]
Sorry, that solution is for the multiple button pressing. Anyway `keyPressed()` keeps triggering if the key is pressed.

**Comment by Derrreks** [comment]
So can this issue be closed? Does keyPressed() continually get called if a key is held down?

**Comment by pr0ves** [comment]
Yes, it does. Made a test [here](https://github.com/pr0ves/exjava/tree/master/ButtonCatcher/src)

**Comment by Derrreks** [comment]
Okay great. I'll close it then.
