### ISSUE TITLE
Velocity and Forces

### ISSUE THREAD

**Issue by Derrreks** [Derrreks/SideScroller#19]
Do we really the interface Velocity and Forces or could we just be putting all this stuff into player or gamepanel or somewhere else? If we do need it who would use it?

**Comment by pierfier** [comment]
You could do that, or put Velocity and Forces within Camera. Also, are you guys gettings the game to play? All I get is a small black box on the top left corner

**Comment by Derrreks** [comment]
I don't have it downloaded to my computer so I can't test it. Does the startPanel load with a button in the middle of the screen?

**Comment by Derrreks** [comment]
When I test it in netbeans it works.

**Comment by pierfier** [comment]
Shoot, mine is not working. All on the master branch?

**Comment by Derrreks** [comment]
Yeah. We'll have to have Ethan try and see if his works. I can also try and download it and run it.

**Comment by EthanSchoen** [comment]
OK mine works but level1 is disabled and no player appears for level2

**Comment by EthanSchoen** [comment]
maybe zero based return or not?

**Comment by Derrreks** [comment]
I can fix that give me one second.

**Comment by EthanSchoen** [comment]
i did

**Comment by EthanSchoen** [comment]
sorry

**Comment by Derrreks** [comment]
Okay. I think it works if you put a > instead of <=

**Comment by EthanSchoen** [comment]
why isn't player getting placed in tho?

**Comment by Derrreks** [comment]
no idea that doesn't make sense. your version downloaded the level and everything correctly right?

**Comment by EthanSchoen** [comment]
o i see someone commented it out

**Comment by Derrreks** [comment]
wow who did that

**Comment by Derrreks** [comment]
lemme check

**Comment by Derrreks** [comment]
dunno

**Comment by EthanSchoen** [comment]
jumping is broke too

**Comment by Derrreks** [comment]
ugh no. I'm going to dinner then I'll be back to try and fix errors

**Comment by EthanSchoen** [comment]
im out
shits fucked yo

**Comment by Derrreks** [comment]
What doesn't work with it? Do you know?

**Comment by EthanSchoen** [comment]
naa just that jumping dont work but it gets to the method that should do it

**Comment by Derrreks** [comment]
nooooooo okay

**Comment by Derrreks** [comment]
jumping works now. fixed it last night forgot to say it here

**Comment by pierfier** [comment]
Do you guys have the OracleJDK or OpenJDK?

**Comment by Derrreks** [comment]
no idea

**Comment by Derrreks** [comment]
This is all set, I'm gonna close it.
