### ISSUE TITLE
Still cant figure out how to code with this

### ISSUE THREAD

**Issue by EthanSchoen** [Derrreks/SideScroller#2]
Feel bad I haven't done anything but i cant figure how to get into netbeans or anything

**Comment by Derrreks** [comment]
Just like any time you think of something to add just throw the code down. Or you can copy the specific class you're editing into netbeans, edit it, then paste is back.

**Comment by pierfier** [comment]
Is #2 alright?

**Comment by EthanSchoen** [comment]
yeah I guess, was looking at github's features when I opened and closed this
