### ISSUE TITLE
Multiple Button Presses

### ISSUE THREAD

**Issue by Derrreks** [Derrreks/SideScroller#21]
We need to make it so that if someone presses another button while they already have on being held down, it will do both of them (such as moving right and jumping at the same time).

**Comment by pierfier** [comment]
I would try threading

**Comment by Derrreks** [comment]
I've been working on it but so far it's not working for me.

**Comment by pierfier** [comment]
I will give this a go. I got it to work! For my version of java, the file names need to be case sensitive. I changed level to Level. It looks great so far!

**Comment by Derrreks** [comment]
Okay good luck. I tried it last night and it's not easy

**Comment by pierfier** [comment]
I will also prevent it from having infinite jumps by checking if the player has already tried to jump

**Comment by Derrreks** [comment]
Yeah you can just check to see if they aren't on the ground. If they aren't then they can't jump.

**Comment by pierfier** [comment]
I have also been checking code that I had for another SideScroller Game, and I have all of the gravity and movement code in the Player class. Would that be ok to do? It would allow better interfacing with the Velocity and Forces class if we were planning on keeping it

**Comment by Derrreks** [comment]
Does it work a lot better than what we have already?

**Comment by pierfier** [comment]
Its faster. Although, the collision was done by pixels instead of the whole space it occupied. The graphics during the collision is much cleaner the way it is now, so I do not want to mess with that.

**Comment by pierfier** [comment]
How do you stop the Players lateral movement? I can't find that code

**Comment by pierfier** [comment]
Never mind

**Comment by Derrreks** [comment]
It stops automagically

**Comment by Derrreks** [comment]
If you think you can combine your old way and what we have now so that it's faster but sitll works you could try that

**Comment by pierfier** [comment]
Yeah, that's why it is so smooth. I will try, but it might not be clean

**Comment by Derrreks** [comment]
JUst put it altogether, make sure it works, and then update it. We can clean it up later but for now just make it work with what we have.

**Comment by Derrreks** [comment]
Actually don't commit it. Whatever changes you make make a merge request so that me and Ethan can see it and test it to before we commit.

**Comment by pierfier** [comment]
I got it to work!

**Comment by pierfier** [comment]
Do we want to merge the two branches? We could clean it at one point, but for now it looks good. There is even some acceleration towards the beginning which is very realistic.

**Comment by Derrreks** [comment]
If it works and doesn't mess with anything we already have sure merge it.

**Comment by Derrreks** [comment]
What about multiple button pressing?

**Comment by pierfier** [comment]
I sort of did it. I was able to have it for the player to move in a direction and then jump at the same time

**Comment by pierfier** [comment]
I thought that is what you guys meant by multiple button pressing

**Comment by Derrreks** [comment]
Yeah like if you're moving right and you hit jump you would go up and right at the same time.

**Comment by pierfier** [comment]
Oh, it does that. Does it?

**Comment by pierfier** [comment]
I put that stuff in the MultPress branch

**Comment by Derrreks** [comment]
I don't know. I'm working on something else right now.

**Comment by Derrreks** [comment]
I'm adding a design behind the startPanel and levelSelectPanel right now.

**Comment by pierfier** [comment]
Ok, sounds good. I will try to do something in the Camera class

**Comment by Derrreks** [comment]
Okay

**Comment by Derrreks** [comment]
Did you merge your changes?

**Comment by Derrreks** [comment]
I just tested it and it definitely works better; nice stuff.

**Comment by Derrreks** [comment]
I'm going to close this because it seems to work pretty well for now.
