### ISSUE TITLE
Rescalable

### ISSUE THREAD

**Issue by Derrreks** [Derrreks/SideScroller#22]
We need to make certain things like speed and velocity scalable to how big the block size is because right now if the blocks are huge they would be slow but if the blocks are small they're really fast.

**Comment by Derrreks** [comment]
I can work on this later.

**Comment by pierfier** [comment]
We should have an init method that sets all of these game constants at the
start of the game

**Comment by Derrreks** [comment]
Yeah I have an idea for this I got it

**Comment by Derrreks** [comment]
I'm working on this right now

**Comment by Derrreks** [comment]
we good
