### ISSUE TITLE
File Path

### ISSUE THREAD

**Issue by pierfier** [Derrreks/SideScroller#27]
The settings file cannot be found because the raw directory is used. There should be a way to get to the parent directory and then to the settings folder with settings.txt

**Comment by Derrreks** [comment]
it will be found if you put it as src\\levels\\level1 or whatever. it only needs to be changed to the absolute directory if you want to build it and get the jar file so we're good for now.

**Comment by pierfier** [comment]
For some reason, the levels work, but the settings does not
