### ISSUE TITLE
Running this thing

### ISSUE THREAD

**Issue by EthanSchoen** [Derrreks/SideScroller#4]
Is anyone able to run this and get a window to appear? Because I think that should be our main priority from now on before we add code or add more classes.

**Comment by Derrreks** [comment]
Yep I updated it earlier today. Using the code in the application class a frame will appear with the startPanel using CardLayout and we can easily switch now between that panel and the gamePanel.

**Comment by EthanSchoen** [comment]
so it runs now?

**Comment by Derrreks** [comment]
That part at least works. I have just the Frame, StartPanel, GamePanel, and Application classes in Netbeans and when I run it it works like we want it to so we're good there.

**Comment by EthanSchoen** [comment]
ok cool
