### ISSUE TITLE
event Class

### ISSUE THREAD

**Issue by Derrreks** [Derrreks/SideScroller#6]
Where do you guys think we should have the event class used? It could be maybe in the player glass or on the panel or in application. What do you think?

**Comment by pierfier** [comment]
It could actually be in both, but maybe it should go in the panel class.

**Comment by Derrreks** [comment]
I was thinking panel as well, so it can just update and repaint itself.

**Comment by Derrreks** [comment]
We'll do gamePanel yeah.
